#!/bin/bash

if [[ $1 == "nvidia" ]]; then
        LINE_OUTPUT_CLASS=$(grep -n "OutputClass" /usr/share/X11/xorg.conf.d/nv>
        LINE_END_SECTION=$(grep -n "EndSection" /usr/share/X11/xorg.conf.d/nvid>
        if [[ $((LINE_OUTPUT_CLASS)) -lt $((LINE_END_SECTION)) ]]; then
                cp -p /usr/share/X11/xorg.conf.d/nvidia.conf /etc/X11/xorg.conf>
                sed -i "$LINE_END_SECTION i\        \Option \"PrimaryGPU\" \"ye>
    fi
fi

if [[ $1 == "offload" ]]; then
        rm /etc/X11/xorg.conf.d/nvidia-gpu-primary.conf
fi
